### ISSUE TITLE
Added images are not persisted

### ISSUE THREAD

**Issue by npranami** [rajatkulkarni95/octarine-feedback#12]
1. Copy any image to clipbaord
2. Paste it in one of the notes. At this point we can view the image.
3. Save the note and restart application. Now the image doesn't render. We see a "not found image icon"

**Comment by rajatkulkarni95** [comment]
Hey! Was just reported yesterday by another user.

Working on a fix, should most likely be out today! Seems like a recent update messed the clipboard pasting, while not affecting drag and drop.

**Comment by npranami** [comment]
This has been there from the beginning when I started trying 1 month back.

**Comment by rajatkulkarni95** [comment]
Possible to have been introduced in [0.16.0](https://octarine.app/changelog/0.16.0)

**Comment by rajatkulkarni95** [comment]
@npranami Fixed in [0.17.3](https://octarine.app/changelog/0.17.3)
