### ISSUE TITLE
Link from `Daily Desk` to a note in a folder doesn't work

### ISSUE THREAD

**Issue by davinkevin** [rajatkulkarni95/octarine-feedback#15]
Hello 👋 

I would like to link a note stored in a folder, and the system seems to fail and instead of creating a link, it creates a new note at the root level. See in video 

https://github.com/user-attachments/assets/42fc6458-aa76-4521-a214-53d2657e58dd

If you need more information, let me know

**Comment by rajatkulkarni95** [comment]
Is there a `space` after the folder names? I'm guessing that's causing the issue?

Can you try removing the space after `sociaux` folder and `patron`?

**Comment by davinkevin** [comment]
> Is there a `space` after the folder names? I'm guessing that's causing the issue?
> 
> Can you try removing the space after `sociaux` folder and `patron`?

I confirmed, we had a space in each folder name, at the end. I removed them directly (no `refresh`), and it works now. 

If you want me to do more test, let me know. If you want to close the issue, feel free to do so.

**Comment by rajatkulkarni95** [comment]
Nope that should be. Glad it works.

Thanks for reporting the bug! Hope you are enjoying the app!
