### ISSUE TITLE
The rendering looks off when highlights are used in a check list

### ISSUE THREAD

**Issue by npranami** [rajatkulkarni95/octarine-feedback#16]
<img width="614" alt="image" src="https://github.com/user-attachments/assets/200e20ec-2bf0-4ba3-9103-fa4b0f604128">
I am unable to use the highlight and add a link to another note in a task item

Steps to reproduce 
1. Create a task item
2. Highlight the text 
3. Add a link to another note.

Another bug/issue is
1. Create a task item
2. Highlight the text
3. Try to add some unhighlighted text next to it.

**Comment by rajatkulkarni95** [comment]
Do you have a reproducible video you can share?

Links can't be created ON a highlight/code/bold text. They are their own nodes.

A video might help understand what the issue could be

**Comment by npranami** [comment]
you can see the difference between 1,3 and 2 in above screenshot

**Comment by rajatkulkarni95** [comment]
> you can see the difference between 1,3 and 2 in above screenshot

Yes but i have no idea how you reached that point.

A video would help me debug instead of giving on a wild goose chase

**Comment by rajatkulkarni95** [comment]
Closing since no info provided, and there's no actionable steps.

Feel free to open when you can add more details in.
