### ISSUE TITLE
[Bug] Code Blocks Language syntax overlap

### ISSUE THREAD

**Issue by Varashines** [rajatkulkarni95/octarine-feedback#18]
**Describe the bug**
Code Blocks in Hyperlinked notes have syntax overlaping with code when hovered over when using fonts like karla. Works fine with Inter

**To Reproduce**
1. Go to settings
2. Change editor font to karla

**Expected behavior**
No overlap

**Screenshots**
<img width="585" alt="image" src="https://github.com/user-attachments/assets/c2cb6ceb-a894-4318-9426-cf513a98665b">

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Version [15.2]

**Additional context**

**Comment by rajatkulkarni95** [comment]
Can you paste the markdown content as is of the linked note? The one with the codeblock.

Remove sensitive data if any, but do not change any formatting.

Open the note in a regular text editor or vscode and paste it from there

**Comment by Varashines** [comment]
```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = np.random.randint(1,100,(30,5))

df = pd.DataFrame(data, columns = "a b c d e".split())
df.head()
df.shape
df.info()
corr = df.corr(numeric_only = True)

plt = sns.heatmap(corr, cmap = "Blues", annot = True)
plt

sns.histplot(df['a’])
sns.jointplot(x = 'a', y = ‘b’, data = df, kind = 'scatter')
sns.kdeplot(df['a'])
```

**Comment by rajatkulkarni95** [comment]
What happened to the `Scripting` header and the `- Testing`?

**Comment by Varashines** [comment]
> What happened to the `Scripting` header and the `- Testing`? Also can you post a screenshot of how it looks with Inter?

Updated

**Comment by rajatkulkarni95** [comment]
Weird, I can't seem to get that cut off even in Karla
<img width="1043" alt="Screenshot 2024-12-04 at 22 54 51" src="https://github.com/user-attachments/assets/7c8479fc-e6b8-4d45-844c-c349141090ec">

**Comment by rajatkulkarni95** [comment]
Closing this, as it seems like a non-issue

**Comment by Varashines** [comment]
I was able to replicate this. It only happens when code block width is more than hover area. Not related to font at all.
<img width="411" alt="image" src="https://github.com/user-attachments/assets/2414595d-913b-4e06-b205-8aea92007c3a">
<img width="411" alt="image" src="https://github.com/user-attachments/assets/4f75097b-6560-4f0b-b8e1-76466dbdde2f">

**Comment by rajatkulkarni95** [comment]
Still can't seem to reproduce this even with longer codeblocks and wider ones. I'm going to close this off for now.
