### ISSUE TITLE
version 0.14.3 can't edit notes under MacOS Monterey 12.6.7

### ISSUE THREAD

**Issue by gadmyth** [rajatkulkarni95/octarine-feedback#2]
In a note, when click keyboard's key, only the "ENTER" key can open a new line in editor, other keyboard's keys have no response.

**Comment by gadmyth** [comment]
My safari's version is: 17.4.1 (17618.1.15.111.8, 17618)

**Comment by rajatkulkarni95** [comment]
> My safari's version is: 17.4.1 (17618.1.15.111.8, 17618)

Hmm then maybe it isn't a safari issue. Cause I'm on `17.2.1`, so that isn't the issue. I'll check some more, and get back to you?

**Comment by erguotou520** [comment]
The same issue. Mac Monterey, 12.5. Safari 15.6.

**Comment by gadmyth** [comment]
Version 0.15.1 (20240512.170103)，can't work under MacOS Monterey 12.6.7，when open a note, shows the error message:
Application error: a client-side exception has occurred (see the browser console for more information)

Is there any keyboard shortcut to toggle the browser console to see the error?

<img width="767" alt="image" src="https://github.com/rajatkulkarni95/octarine-feedback/assets/435272/71b5cb48-deb2-4be9-92a2-36b29a6864c9">

**Comment by rajatkulkarni95** [comment]
Weird. Are you on `v0.15.1`? Can you try downloading and reinstalling the version from the website? https://octarine.app/releases

**Comment by erguotou520** [comment]
![image](https://github.com/rajatkulkarni95/octarine-feedback/assets/7945757/7d054744-a908-4b05-b137-fdbea9ea71fb)

version `0.15.1`

**Comment by rajatkulkarni95** [comment]
> ![image](https://github.com/rajatkulkarni95/octarine-feedback/assets/7945757/7d054744-a908-4b05-b137-fdbea9ea71fb)
> 
> 
> 
> Version `0.15.1`.
> 
> 
> 
> If you can share the source code, maybe we can fix it together.

I'll take a look. Unfortunately there's no plans for open sourcing the app, so sharing the code is out of the question.

**Comment by rajatkulkarni95** [comment]
Just tried creating a new workspace, and it worked fine. Can you try creating a new workspace and check? @gadmyth @erguotou520

**Comment by rajatkulkarni95** [comment]
> Is there any keyboard shortcut to toggle the browser console to see the error?

The framework disables it on prod environments. The default Cmd Option I doesn't work

**Comment by erguotou520** [comment]
@rajatkulkarni95 It also show the same error when create a new workspace.

**Comment by rajatkulkarni95** [comment]
@gadmyth @erguotou520 Can you paste the file content here? Cause here's me doing a fresh install, and creating new workspaces with no issues. Would help in debugging.


https://github.com/rajatkulkarni95/octarine-feedback/assets/57321156/0561d6a8-13e7-49cc-8d0d-e3f1d6ab89d8

**Comment by gadmyth** [comment]
When I remove the app ( sudo rm -rf /Applications/Octarine.app/)，and reinstall the Version 0.15.2 (20240516.150227)，and create a new workspace, it still not work.


<img width="1022" alt="image" src="https://github.com/rajatkulkarni95/octarine-feedback/assets/435272/91537ce9-cae3-4c2f-9ef5-47064f586820">

**Comment by rajatkulkarni95** [comment]
@gadmyth Weird why this is happening still. Can you try downloading an older version? This is [v0.14.4](https://pub-3d35bc018fc54f11bde129e3e73e8002.r2.dev/0.14.4%2Fintel%2Foctarine_0.14.4_x64.dmg),

If the popup for `update to new version` shows up, click `No`. And check if this works?

Assuming you are on an Intel Mac due to the old OS. Else here's an [ARM one](https://pub-3d35bc018fc54f11bde129e3e73e8002.r2.dev/0.14.4%2Farm%2Foctarine_0.14.4_aarch64.dmg)

My sentry hasn't been setup properly, so I can't even trace what issue this could be :(

**Comment by gadmyth** [comment]
When install v0.14.4，the error disappeared:

> Application error: a client-side exception has occurred (see the browser console for more information)

but the note can't be edited again.

**Comment by rajatkulkarni95** [comment]
> When install v0.14.4，the error disappeared:
> 
> > Application error: a client-side exception has occurred (see the browser console for more information)
> 
> but the note can't be edited again.

was the note editable in the `v0.15` versions?

**Comment by gadmyth** [comment]
Yes, the error appeared when v0.15.2 was installed

**Comment by rajatkulkarni95** [comment]
@gadmyth @erguotou520  Hey, i don't expect miracles, but can you pick the latest version from the app, and see if that works out?

**Comment by erguotou520** [comment]
I didn't use this app now.
