### ISSUE TITLE
[Feature Request] Lock Notes

### ISSUE THREAD

**Issue by janiosarmento** [rajatkulkarni95/octarine-feedback#20]
Before opening this issue and suggesting a new feature, I searched around, and it seems no one else asked that before me.

It's a bit frustrating when I mistakenly overwrite parts of a note. For example, when I don't see that the focus is on Octarine instead of Mail.

A simple solution would be to create a property called "locked" for the notes. When active, the note can be viewed only, not modified.

Thanks for this excellent piece of software. After using the free version for a few hours, I was convinced I should support development by acquiring a "Pro" license.

Thanks for considering this!

**Comment by rajatkulkarni95** [comment]
Excellent suggestion! Was already on the roadmap, but can prioritise it soon!

<img width="618" alt="Screenshot 2024-12-09 at 09 24 31" src="https://github.com/user-attachments/assets/30bd49de-06c9-420b-94a5-53bcfb348f5d">

The way it would behave is similar to pinning notes
<img width="361" alt="Screenshot 2024-12-09 at 09 25 46" src="https://github.com/user-attachments/assets/648b9d95-eb47-45d5-88d9-134598e4971d">


Really appreciate you purchasing a Pro License! Tons of stuff incoming, and thanks for supporting the app!

**Comment by rajatkulkarni95** [comment]
Still some code cleanup needs to be done, but here's a quick preview

https://github.com/user-attachments/assets/9f83899d-1a91-43c5-8cd7-6bd7e7846a6e

**Comment by rajatkulkarni95** [comment]
This is out now in [0.20.0](https://octarine.app/changelog/0.20.0). Thanks for pushing me to prioritise this! Hope this helps!
