### ISSUE TITLE
[Feature Request] Table of Contents

### ISSUE THREAD

**Issue by janiosarmento** [rajatkulkarni95/octarine-feedback#21]
I didn't find another request for this feature, but I think an automatic table of contents would be lovely.

Octarine could display an outline of the document or an unordered list with section headings so that the user can quickly get a general overview. It could be placed on the sidebar.

If you want me to explain it better, please let me know.

Thanks!

**Comment by rajatkulkarni95** [comment]
It already is present? So if you open the right sidebar, the 3rd button shows the outline!

<img width="983" alt="Screenshot 2024-12-10 at 23 26 48" src="https://github.com/user-attachments/assets/6d7a01f8-9634-441a-b275-4a56d9f283c4">

**Comment by rajatkulkarni95** [comment]
Maybe it can be better discoverable (via the CMD K bar as well)?

**Comment by janiosarmento** [comment]
Shame on me! I looked at the sidebar one million times and never saw the list icon until you pointed it out!

Thanks, and sorry for the false alarm!
