### ISSUE TITLE
[Bug] Crash when typing into a recently created note

### ISSUE THREAD

**Issue by dserodio** [rajatkulkarni95/octarine-feedback#22]
**Describe the bug**
I was typing into an untitled, recently created note and Octarine crashed

**To Reproduce**
Sorry, I don't have reproduction steps

**Desktop (please complete the following information):**
 - OS: macOS 15.2
 - Version [e.g. 0.19.2]

**Additional context**
[Crash Report](https://github.com/user-attachments/files/18128006/octarine-crash.txt)

**Comment by rajatkulkarni95** [comment]
Should be fixed when the fix for #24 goes through

**Comment by rajatkulkarni95** [comment]
This has been fixed in [0.20.1](https://octarine.app/changelog/0.20.1). However, if you still see issues, feel free to reopen this issue or create a new one
