### ISSUE TITLE
[Bug] Crash when dragging to move a new note

### ISSUE THREAD

**Issue by dserodio** [rajatkulkarni95/octarine-feedback#24]
**Describe the bug**

I had just created a not but hadn't given it a title yet. I added a title, and was dragging the newly created note into a folder when Octarine crashed.

**Desktop (please complete the following information):**
 - OS: macOS 15.2
 - Version 0.20.0

**Additional context**

[crashdump.txt](https://github.com/user-attachments/files/18169386/octarine-2024-12-17-144047.txt)

**Comment by rajatkulkarni95** [comment]
Okay was able to reproduce it. I think it's an `instant action` issue. Seems like the renaming function is slow, so when it moves it instantly there's a `path` issue.

Here's 2 videos, one where the renaming and moving is done near instantly (crashes the app), and one where the move is done 1 sec after the renaming (doesn't crash)

1. Instant and Crashes

https://github.com/user-attachments/assets/90ea1374-15b7-405e-80d4-b3dc8f63adfb


2. Slight delay and no crash

https://github.com/user-attachments/assets/5e1e4e02-96bd-428b-8c09-b95068699735





I'll check the function.

**Comment by rajatkulkarni95** [comment]
@dserodio Have a fix for this. Will be released in the next version this weekend.

https://github.com/user-attachments/assets/0a5f53ca-dbef-4d2b-8d51-fa93f9990132

**Comment by dserodio** [comment]
Thanks for the fast response, as usual

**Comment by rajatkulkarni95** [comment]
This has been fixed in [0.20.1](https://octarine.app/changelog/0.20.1). However, if you still see issues, feel free to reopen this issue or create a new one
