### ISSUE TITLE
[Bug] Cursor placement with Quick Actions message seems wrong

### ISSUE THREAD

**Issue by AntoineQ1** [rajatkulkarni95/octarine-feedback#27]
**Describe the bug**
When on a new line, the message "Press / for quick actions" appears.
However, the cursor is at the end of that text which is quite disturbing. _(For instance, this behavior is different from Notion behavior)_
Indeed, when typing "/", the cursor then abruptly returns to its normal position.
Yet, I am not sure whether it's a bug or if it is intended.

**To Reproduce**
1. Open a note
2. Press "Enter" to go to a new line

**Expected behavior**
The cursor should stay on the left of the page and on the left of the "Press / for quick actions" text.

**Screenshots**
![image](https://github.com/user-attachments/assets/54620002-b9e1-4393-9dc9-d582c993e51d)
On this screenshot, one can see the cursor on the right of the text.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version : 0.20.1

**Comment by rajatkulkarni95** [comment]
Seems like a Windows related issue, since it isn't the case on Mac. I'll investigate, thanks!
<img width="639" alt="Screenshot 2024-12-28 at 23 04 48" src="https://github.com/user-attachments/assets/e7970fb3-9f69-4db7-bcbe-77ab8a350137" />

**Comment by rajatkulkarni95** [comment]
@AntoineQ1 This has been fixed. Please download the latest release from https://octarine.app/beta-releases to install it.
