### ISSUE TITLE
[Bug] Spellcheck always active

### ISSUE THREAD

**Issue by AntoineQ1** [rajatkulkarni95/octarine-feedback#28]
**Describe the bug**
Spellcheck always active even when disabled in the app settings.

**To Reproduce**
1. Go to "Workspace Settings > Editor"
2. Set "Spellcheck" feature to "Off"
3. Go to a note
4. Observe that the dotted underline is still present

**Expected behavior**
The feature should be disabled.

**Screenshots**
![image](https://github.com/user-attachments/assets/116400c2-ee27-425b-bc03-336de6895ea7)
![image](https://github.com/user-attachments/assets/3a5f3580-5304-4817-8fb4-e38d750f817b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version : 0.20.1

**Comment by rajatkulkarni95** [comment]
Okay, so in Mac, you never see the dotted lines, even with spellcheck on, and in Windows it's the opposite! Will investigate both OSes

**Comment by rajatkulkarni95** [comment]
@AntoineQ1 This has been fixed. Please download the latest release from https://octarine.app/beta-releases to install it.

I'm currently in the process of fixing auto-updates for Windows, so for the time being you'd need to manually download and update it.
