### ISSUE TITLE
[Bug] Vertical placeholder text when using To-Do lists

### ISSUE THREAD

**Issue by AntoineQ1** [rajatkulkarni95/octarine-feedback#29]
**Describe the bug**
When creating a To-Do list, the placeholder text ("Presss / for quick actions") is displayed vertically (one letter per line).

**To Reproduce**
1. Go to a note
2. Create a To-Do list

**Expected behavior**
The text should display correctly (horizontally).

**Screenshots**
![image](https://github.com/user-attachments/assets/96f39b32-c2e9-4410-8dcc-5a7ed63b4dfa)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version : 0.20.1-2912

**Comment by rajatkulkarni95** [comment]
Seems like the fix for #27 broke this! :(

**Comment by rajatkulkarni95** [comment]
Fixed! Please download the `3012` release from https://octarine.app/beta-releases

![Screenshot 2024-12-30 102006](https://github.com/user-attachments/assets/a67a6e25-6ebe-46ea-a59e-a45c6970c9d1)

![Screenshot 2024-12-30 101959](https://github.com/user-attachments/assets/cdde8e37-aa9a-4e0e-9cd3-82b66c1c8e99)
