### ISSUE TITLE
[Bug] Uploaded Image is Broken

### ISSUE THREAD

**Issue by ramskiedrew06** [rajatkulkarni95/octarine-feedback#31]
**Describe the bug**
When I tried to drag and drop the image, it shows a broken image instead the actual image

**To Reproduce**
1. I opened my file explorer
2.  Choose the image I wanted to upload, in this case, I just use one sample image
3. It shows broken image

**Expected behavior**
The image should be viewable as describe in website

**Screenshots**

https://imgur.com/a/uD8TFs1

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 0.20.1

**Additional context**
N/A

**Comment by rajatkulkarni95** [comment]
Thanks! I'll take a look. Seems to be an issue with either permissions or uploading! Since it works fine on Mac.
<img width="968" alt="Screenshot 2024-12-29 at 23 18 03" src="https://github.com/user-attachments/assets/59b25f8e-a440-41e3-9967-a68bb23e8c5c" />

**Comment by rajatkulkarni95** [comment]
Fixed. Please download the `3012` release from https://octarine.app/beta-releases

![Screenshot 2024-12-30 101626](https://github.com/user-attachments/assets/52e4b7aa-a873-49bb-ae89-9a6e9d6e91f7)

**Comment by ramskiedrew06** [comment]
Awesome. Thanks. Upload images are working perfectly fine now.
