### ISSUE TITLE
Tab not working as expected when typing code in a code block

### ISSUE THREAD

**Issue by pixmin** [rajatkulkarni95/octarine-feedback#4]
I create a new code block with ```
I then start writing code, but if I press TAB to add a tabulation, instead of adding a tabulation, it goes to another element and then what I'm typing goes in the search left sidebar.

**Comment by rajatkulkarni95** [comment]
Hello! Yes currently pressing tab inside a codeblock doesn't indent the code (like code editors would)

This is a limitation of prosemirror at the time being, but I am currently looking at ways to fix it
