### ISSUE TITLE
AppImage - Workspace Location doesn't open GTK folder selection

### ISSUE THREAD

**Issue by celi28** [rajatkulkarni95/octarine-feedback#6]
### Issue
When opening the AppImage during the "Create New Workspace", the "choose folder" button doesn't open GTK dialog to choose path.

### Environment
__Version:__ 0.16.2
__Deployment mode:__ AppImage
__OS:__ Archlinux - Linux 6.10.4-zen2-1-zen
__Dependancy locally installed__:
- cairo 1.18.0-2
- desktop-file-utils 0.27-1
- gcc-libs 14.2.1+r32+geccf707e5ce-1
- gdk-pixbuf2 2.42.12-1
- glib2 2.80.4-1
- glibc 2.40+r16+gaa533d58ff-2
- gtk3 1:3.24.43-1
- hicolor-icon-theme 0.18-1
- libsoup3 3.4.4-1
- openssl 3.3.1-1
- webkit2gtk-4.1 2.44.2-1

### Step to reproduce
1. Open AppImage
2. Create New Workspace
3. Click on Workspace Location - Choose folder

![image](https://github.com/user-attachments/assets/47548632-487f-4894-9aa6-6b4f26b88bfd)

**Comment by rajatkulkarni95** [comment]
Thanks for the detailed report. I'll try debugging this by pulling a VM. Ideally dialog should open across all OSes since it does nothing special.

**Comment by celi28** [comment]
With pleasure. Feel free to ask any complementary information.
A fallback alternative under Linux would may be to allow path edit as text box.

**Comment by rajatkulkarni95** [comment]
> With pleasure. Feel free to ask any complementary information.
> 
> A fallback alternative under Linux would may be to allow path edit as text box.
> 
> 

Yep! Since the dialog just gives back the path string anyway.

And i have checks in place to see if the path exists or not.

Will spend some time today to see if the dialog is salvageable or will give the fallback!

Ty for patience!

**Comment by rajatkulkarni95** [comment]
@celi28  I'm thinking about something like this, should work out IMO. I'll add some validations in, but since it's not a frequent use case, I can go a bit lenient 

https://github.com/user-attachments/assets/fc41beea-5268-4bfd-9ccb-83a8128251f6

**Comment by rajatkulkarni95** [comment]
@celi28 Would you be willing to try this [version out ](https://pub-3d35bc018fc54f11bde129e3e73e8002.r2.dev/linux%20release/Octarine_0.16.3_amd64.AppImage)

It has the above thing in place, let me know if it works out for you. This is a pre-release, so if it does work out for you, I can package it tomorrow and release it with the other improvements.

Feedback is appreciated!

**Comment by celi28** [comment]
> @celi28 Would you be willing to try this [version out ](https://pub-3d35bc018fc54f11bde129e3e73e8002.r2.dev/linux%20release/Octarine_0.16.3_amd64.AppImage)
> 
> It has the above thing in place, let me know if it works out for you. This is a pre-release, so if it does work out for you, I can package it tomorrow and release it with the other improvements.
> 
> Feedback is appreciated!

Works fluently. Thanks for your quick fix :)

**Comment by rajatkulkarni95** [comment]
> > @celi28 Would you be willing to try this [version out ](https://pub-3d35bc018fc54f11bde129e3e73e8002.r2.dev/linux%20release/Octarine_0.16.3_amd64.AppImage)
> 
> > 
> 
> > It has the above thing in place, let me know if it works out for you. This is a pre-release, so if it does work out for you, I can package it tomorrow and release it with the other improvements.
> 
> > 
> 
> > Feedback is appreciated!
> 
> 
> 
> Works fluently. Thanks for your quick fix :)
> 
> I let you close this issue when you will push back the fix.

Lets goooooo! I'll build and deploy 0.16.3 for everyone. Will comment here when it's up so you can also download it since there's a few things added in post this beta build.

Appreciate It!

**Comment by rajatkulkarni95** [comment]
Released in [v0.16.3](https://octarine.app/changelog/0.16.3).

Please download the latest version! @celi28
