### ISSUE TITLE
Octarine 0.16.4 Linux AppImage CPU usage

### ISSUE THREAD

**Issue by patatetom** [rajatkulkarni95/octarine-feedback#9]
hi,
**`octarine` looks really good** :+1: , but on my workstation, I've noticed with `top` that even when it's not in use (background or reduced), it takes up nearly 25% of the CPU (i7), which causes the CPU to heat up and my battery to melt very quickly.
regards, lacsaP.

**Comment by rajatkulkarni95** [comment]
Hmm weird, it shouldn't take resources like that. Here's it in the background on my mac
<img width="1063" alt="Screenshot 2024-08-31 at 08 31 25" src="https://github.com/user-attachments/assets/f722f30f-96b2-4e92-95ad-b2675ce0c965">

Does it happen all the time? Just sometimes? Can you send a screenshot of the activity?

**Comment by patatetom** [comment]
here's a screenshot :
![octarine 0 16 4](https://github.com/user-attachments/assets/ec8706d7-7b8e-478d-9c0f-2c46f7e42957)

`octarine`'s consumption _oscillates_ between 15% and 30%.
_oscillated_, because I've just migrated to the new version 0.17.1 and CPU usage is back to normal.

_a small remark about the update : `octarine`'s update search is disabled, but it did notify me of the availability of a new version..._

**Comment by rajatkulkarni95** [comment]
@patatetom So it's better now with `v0.17.1`?

> a small remark about the update : octarine's update search is disabled, but it did notify me of the availability of a new version...

How do you disable it? Since there's no option to not look for updates?

**Comment by patatetom** [comment]
yes, `v0.17.1` est OK 👍 

_you're right, ignore my remark : I got mixed up with another application that was open in parallel. note that this deactivation option could be useful (offline)..._

**Comment by rajatkulkarni95** [comment]
Yep a toggle to disable and one for opting into beta channels/update is being worked on!

Closing this ticket for now!
